### ISSUE TITLE
Support for Singletons?

### ISSUE THREAD

**Issue by andrevvm** [pauloamgomes/ImageStyles#13]
This is such a great add-on, but wondering what it would take to add Singleton support? Looked into the source and couldn't quite get there myself. Thanks!

**Comment by pauloamgomes** [comment]
Hi @andrevvm , right now Singletons are not supported, the Addon was created before the change from Regions to Singletons in Cockpit. In such case is something that I'm planning to add.

**Comment by pauloamgomes** [comment]
Well, since the structure of singletons is quite similar to collections it was possible to do most of the work in the singleton.saveData.before hook (commit  [e2eddef](https://github.com/pauloamgomes/ImageStyles/commit/e2eddefba285faf916b645a14917d031f6fda943) ) so same behaviour should be expected on singletons, if you define any image field (image, asset, gallery) with a styles array it should return the generated styles.

**Comment by andrevvm** [comment]
@pauloamgomes Works like a charm, thank you!
